name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Instalar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm install

    - name: Build da aplicação React
      run: npm run build

    - name: Publicar artefatos
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build

  cleanup:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: GIT commit and push all changed files
      env: 
        CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
        CI_COMMIT_AUTHOR: Continuous Integration
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push

  deploy:
    needs: cleanup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Download artefatos
      uses: actions/download-artifact@v2
      with:
        name: build
        path: build

    - name: Push para a branch main
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git fetch
        git branch
        git checkout main
        git add .
        git commit -m "Atualizar build"
        git push
