name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Instalar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm install

    - name: Build da aplicação React
      run: npm run build

    - name: Publicar artefatos
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build

  cleanup:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Excluir todos os itens da branch main
      run: |
        git clone https://github.com/WandenDourado/OpenHouse.git
        cd OpenHouse        
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout main
        git rm -rf .
        git commit -m "Limpar a branch main"
        git push https://$GIT_USERNAME:$GIT_PASSWORD@github.com/WandenDourado/OpenHouse.git main

  deploy:
    needs: cleanup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Download artefatos
      uses: actions/download-artifact@v2
      with:
        name: build
        path: build

    - name: Push para a branch main
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git fetch
        git branch
        git checkout main
        git add .
        git commit -m "Atualizar build"
        git push
